---
caddy:
  # Static config that will be appended to the generated Caddyfile
  # e.g acme etc.
  # Templating is supported.
  static_config: |
    # Authelia Portal.
    auth.{{ global.base_domain }} {
            reverse_proxy 172.17.0.1:9091
    }
  # Dynamic config that will be appended to the generated Caddyfile
  # e.g reverse_proxy etc.
  hosts:
    groups:
      "*Arr":
        type: group
        base_upstream: 172.17.0.1
        domains:
          - domain: "sonarr.{{ global.base_domain }}"
            upstream_port: 8989
          - domain: "radarr.{{ global.base_domain }}"
            upstream_port: 7878
          - domain: "readarr.{{ global.base_domain }}"
            upstream_port: 8787
          - domain: "lidarr.{{ global.base_domain }}"
            upstream_port: 8686
        use_authelia: false
    apps:
      "Jellyfin":
        type: app
        domain: "jelly.{{ global.base_domain }}"
        upstream: 172.17.0.1:8096
        use_authelia: false

      "Jellyseerr":
        type: app
        domain: "jellyseerr.{{ global.base_domain }}"
        upstream: 172.17.0.1:5055
        use_authelia: false

      "portainer":
        type: app
        domain: "docker.{{ global.base_domain }}"
        upstream: 172.17.0.1:9000
        use_authelia: false

      "Grafana":
        type: app
        domain: "grafana.{{ global.base_domain }}"
        upstream: 172.17.0.1:3000
        use_authelia: false

      "Mealie":
        type: app
        domain: "mealie.{{ global.base_domain }}"
        upstream: 172.17.0.1:9925
        use_authelia: false

      "Prometheus":
        type: app
        domain: "prom.{{ global.base_domain }}"
        upstream: 172.17.0.1:9100
        use_authelia: false

      "Sabnzbd":
        type: app
        domain: "sab.{{ global.base_domain }}"
        upstream: 172.17.0.1:8080
        use_authelia: false

      "Seafile":
        type: app
        disable_dns_challenge: true
        domain: "sea.cloud.yuri.li"
        upstream: 172.17.0.1:8947
        use_authelia: false
        
      "Linkding":
        type: app
        disable_dns_challenge: true
        domain: "dash.cloud.yuri.li"
        upstream: 172.17.0.1:8948
        use_authelia: false

      "QBittorrent":
        type: app
        domain: "torrent.{{ global.base_domain }}"
        upstream: 172.17.0.1:8200
        use_authelia: false