---
# tasks file for docker
- name: Deploy container if its an app
  include_tasks: container.yml
  when: app.type == "app"

- name: Deploy compose stack if its a stack
  include_tasks: compose.yml
  when: app.type == "group"