name: Run Ansible

on:
  push:
    branches:
      - main
    paths:
      - roles/**
      - vars/**
      - .github/workflows/ansible.yml

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key for the server 
        uses: shimataro/ssh-key-action@v2 
        with: 
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Ansible and Caddy Ansible
        run: |
          sudo apt update
          sudo apt install software-properties-common
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible
          ansible-galaxy install caddy_ansible.caddy_ansible 
          ansible-galaxy collection install community.docker

      - name: Run Ansible Playbook
        run: |
          echo ${{ secrets.ANSIBLE_VAULT_PASSWORD }} > .vault_pass.txt
          ansible-playbook -i inventory.yml playbook.yml
          rm .vault_pass.txt
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          ANSIBLE_VAULT_PASSWORD_FILE: .vault_pass.txt
      
